### ISSUE TITLE
Azure AD logins stuck

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-ad-plugin#106]
<p>We use Azure AD authentication and in general it works fine, but today morning on one of our instances it stopped working, making logins impossible. The symptom is that after logging in "nothing is happening", the browser window remains blank, waiting for the page to load. Thread dump (attached) reveals that all the login handling threads (POST /securityRealm/finishLogin) are blocked due to one of them (tid=0x00007f5fe4fd2000) getting blocked for some other reason and thus not releasing the lock the others are waiting for. Restarting the instance "fixed" it, also we have other instances with similar configuration (also using the same Azure AD) that were and still are working perfectly fine.</p>

<p>It would be good to understand what causes this or how to troubleshoot it further.</p>

<p>Thanks,</p>

<p>Istvan</p>

<p> </p>

<p> </p>
<i>[JENKINS-62459] created by pistahh</i>

**Comment by timja** [comment]
Hmm seems to be stuck in the guava cache acquiring an Azure AD access token,

```
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:429)
at java.util.concurrent.FutureTask.get(FutureTask.java:191)
at com.microsoft.azure.credentials.ApplicationTokenCredentials.acquireAccessToken(ApplicationTokenCredentials.java:160)
at com.microsoft.azure.credentials.ApplicationTokenCredentials.getToken(ApplicationTokenCredentials.java:139)
at com.microsoft.azure.credentials.AzureTokenCredentials.getToken(AzureTokenCredentials.java:74)
at com.microsoft.azure.credentials.AzureTokenCredentialsInterceptor.intercept(AzureTokenCredentialsInterceptor.java:36)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at com.microsoft.azure.management.resources.fluentcore.utils.ResourceManagerThrottlingInterceptor.intercept(ResourceManagerThrottlingInterceptor.java:54)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at com.microsoft.azure.management.resources.fluentcore.utils.ProviderRegistrationInterceptor.intercept(ProviderRegistrationInterceptor.java:43)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at com.microsoft.jenkins.azuread.AzureAdPlugin$AzureTelemetryInterceptor.intercept(AzureAdPlugin.java:52)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at com.microsoft.rest.interceptors.BaseUrlHandler.intercept(BaseUrlHandler.java:43)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at com.microsoft.rest.interceptors.RequestIdHeaderInterceptor.intercept(RequestIdHeaderInterceptor.java:29)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
```

I'm going to close this since the libraries are being changed in https://github.com/jenkinsci/azure-ad-plugin/pull/118 and it will be no longer relevant then but please let me know if it re-occurs after upgrading
