### ISSUE TITLE
swarm-client fails to connect with 500 error while using Azure AD Plugin

### ISSUE THREAD

**Issue by timja** [jenkinsci/azure-ad-plugin#109]
<p>Connecting the <em>swarm-client</em> to Jenkins while security is set to <em>Jenkins’ own user database</em> is successful.</p>

<p>Attempting to connect the <em>swarm-client</em> to Jenkins while security is set to <em>Azure Active Directory</em> is unsuccessful.</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">$ java -jar swarm-client-3.13.jar -username USER_UPN -password USER_API_TOKEN -master http:<span class="code-comment">//JENKINS
</span>Aug 24, 2018 11:38:45 PM hudson.plugins.swarm.Client main
INFO: Client.main invoked with: [-username USER_UPN -password PASS -master http:<span class="code-comment">//JENKINS]
</span>Aug 24, 2018 11:38:45 PM hudson.plugins.swarm.Client run
INFO: Discovering Jenkins master
SLF4J: Failed to load class <span class="code-quote">"org.slf4j.impl.StaticLoggerBinder"</span>.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http:<span class="code-comment">//www.slf4j.org/codes.html#StaticLoggerBinder <span class="code-keyword">for</span> further details.
</span>Aug 24, 2018 11:38:45 PM hudson.plugins.swarm.SwarmClient discoverFromMasterUrl
SEVERE: Failed to fetch slave info from Jenkins, HTTP response code: 500
Aug 24, 2018 11:38:45 PM hudson.plugins.swarm.Client run
SEVERE: RetryException occurred
hudson.plugins.swarm.RetryException: Failed to fetch slave info from Jenkins, HTTP response code: 500
at hudson.plugins.swarm.SwarmClient.discoverFromMasterUrl(SwarmClient.java:233)
at hudson.plugins.swarm.Client.run(Client.java:146)
at hudson.plugins.swarm.Client.main(Client.java:119) </pre>
</div></div>
<i>[JENKINS-53234] created by siigna</i>

**Comment by timja** [comment]
See https://github.com/jenkinsci/swarm-plugin/blob/master/docs/security.adoc#authentication you need to use an api token for the password
