### ISSUE TITLE
jenkins-cli fails to auth via SSH on version 157.v2d3d5782a602

### ISSUE THREAD

**Issue by reasland** [jenkinsci/azure-ad-plugin#128]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.277.4
OS: Linux - 3.10.0-957.27.2.el7.x86_64
---
cucumber-reports:5.5.0
trilead-api:1.0.13
jquery:1.12.4-1
structs:1.22
ant:1.11
token-macro:2.15
snakeyaml-api:1.27.0
groovy:2.3
jackson2-api:2.12.3
github:1.33.1
workflow-step-api:2.23
pubsub-light:1.13
script-security:1.76
pipeline-model-api:1.8.4
command-launcher:1.5
http_request:1.9.0
jdk-tool:1.5
jira:3.2.1
apache-httpcomponents-client-4-api:4.5.13-1.0
publish-over:0.22
credentials:2.3.18
git-server:1.9
ssh-credentials:1.18.1
workflow-cps-global-lib:2.18
azure-commons:1.1.2
github-api:1.123
extended-read-permission:3.2
publish-over-ssh:1.22
cloud-stats:0.27
durable-task:1.35
plain-credentials:1.7
workflow-basic-steps:2.23
credentials-binding:1.24
htmlpublisher:1.25
azure-credentials:181.v00b0d97d2686
variant:1.4
azure-vm-agents:777.v276476e1344c
ssh-slaves:1.31.5
matrix-auth:2.6.6
sonar:2.13.1
azure-ad:157.v2d3d5782a602
blueocean-web:1.24.6
workflow-scm-step:2.12
jsch:0.1.55.2
ws-cleanup:0.39
git-client:3.7.0
jacoco:3.1.1
scm-api:2.6.4
blueocean-jwt:1.24.6
display-url-api:2.3.4
view-job-filters:2.3
mailer:1.34
git:4.7.0
maven-plugin:3.10
job-dsl:1.77
favorite:2.3.3
plugin-util-api:2.1.0
blueocean-rest-impl:1.24.6
font-awesome-api:5.15.2-2
popper-api:1.16.1-2
run-condition:0.10
jquery3-api:3.5.1-3
blueocean-git-pipeline:1.24.6
bootstrap4-api:4.6.0-2
javadoc:1.6
echarts-api:5.0.1-1
workflow-api:2.42
pipeline-milestone-step:1.3.2
workflow-support:3.8
checks-api:1.6.1
junit:1.49
blueocean-config:1.24.6
matrix-project:1.18
mercurial:2.14
authentication-tokens:1.4
cloudbees-folder:6.15
blueocean-dashboard:1.24.6
bouncycastle-api:2.20
ace-editor:1.1
workflow-cps:2.90
branch-api:2.6.3
workflow-job:2.40
blueocean-display-url:2.4.1
workflow-multibranch:2.23
okhttp-api:3.14.9
bitbucket-push-and-pull-request:2.7.2
jjwt-api:0.11.2-9.c8b45b8bb173
jenkins-design-language:1.24.6
sse-gateway:1.24
blueocean-core-js:1.24.6
github-branch-source:2.10.2
blueocean-events:1.24.6
pipeline-input-step:2.12
blueocean-i18n:1.24.6
pipeline-stage-step:2.5
blueocean-rest:1.24.6
pipeline-graph-analysis:1.10
blueocean-autofavorite:1.2.4
pipeline-build-step:2.13
blueocean:1.24.6
blueocean-commons:1.24.6
blueocean-pipeline-scm-api:1.24.6
pipeline-model-extensions:1.8.4
workflow-durable-task-step:2.38
pipeline-stage-tags-metadata:1.8.4
pipeline-model-definition:1.8.4
blueocean-pipeline-api-impl:1.24.6
blueocean-github-pipeline:1.24.6
handy-uri-templates-2-api:2.1.8-1.0
cloudbees-bitbucket-branch-source:2.9.7
blueocean-bitbucket-pipeline:1.24.6
blueocean-personalization:1.24.6
blueocean-pipeline-editor:1.24.6
configuration-as-code:1.51
extended-choice-parameter:0.82
lockable-resources:2.10
permissive-script-security:0.6
antisamy-markup-formatter:2.1
resource-disposer:0.15
pipeline-utility-steps:2.7.1
parameterized-scheduler:1.0
conditional-buildstep:1.3.1
parameterized-trigger:2.40
external-monitor-job:1.4
windows-slaves:1.0
ldap:1.26
pam-auth:1.5.1
docker-commons:1.17
docker-workflow:1.26
caffeine-api:2.9.1-23.v51c4e2c879c8
azure-sdk:7.va79ea0a60157


```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Linux, Ubuntu
```

### Reproduction steps

Ran below command to execute groovy scripts with Jenkins CLI

"java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 -ssh -user "devops@trekbikes.net" -i "/var/chef/cache/jenkins-key" groovy

### Results

Expected result:

When I attempt to run a command via Jenkins CLI via SSH I expect it to properly run through the necessary commands 

Actual result:

When attempting to use Jenkins CLI the script immediately fails because "No more authentication methods available"

```
[root@azl-prd-jnks-01 jenkins]# "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 -ssh -user "devops@trekbikes.net" -i "/var/chef/cache/jenkins-key" groovy
May 10, 2021 2:50:41 PM io.jenkins.cli.shaded.org.apache.sshd.common.util.security.AbstractSecurityProviderRegistrar getOrCreateProvider
INFO: getOrCreateProvider(EdDSA) created instance of io.jenkins.cli.shaded.net.i2p.crypto.eddsa.EdDSASecurityProvider
io.jenkins.cli.shaded.org.apache.sshd.common.SshException: No more authentication methods available
	at io.jenkins.cli.shaded.org.apache.sshd.client.session.ClientUserAuthService.tryNext(ClientUserAuthService.java:314)
	at io.jenkins.cli.shaded.org.apache.sshd.client.session.ClientUserAuthService.processUserAuth(ClientUserAuthService.java:251)
	at io.jenkins.cli.shaded.org.apache.sshd.client.session.ClientUserAuthService.process(ClientUserAuthService.java:198)
	at io.jenkins.cli.shaded.org.apache.sshd.common.session.helpers.AbstractSession.doHandleMessage(AbstractSession.java:614)
	at io.jenkins.cli.shaded.org.apache.sshd.common.session.helpers.AbstractSession.handleMessage(AbstractSession.java:547)
	at io.jenkins.cli.shaded.org.apache.sshd.common.session.helpers.AbstractSession.decode(AbstractSession.java:1498)
	at io.jenkins.cli.shaded.org.apache.sshd.common.session.helpers.AbstractSession.messageReceived(AbstractSession.java:508)
	at io.jenkins.cli.shaded.org.apache.sshd.common.session.helpers.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:66)
	at io.jenkins.cli.shaded.org.apache.sshd.common.io.nio2.Nio2Session.handleReadCycleCompletion(Nio2Session.java:301)
	at io.jenkins.cli.shaded.org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:281)
	at io.jenkins.cli.shaded.org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:278)
	at io.jenkins.cli.shaded.org.apache.sshd.common.io.nio2.Nio2CompletionHandler.lambda$completed$0(Nio2CompletionHandler.java:38)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.jenkins.cli.shaded.org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:37)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker$2.run(Invoker.java:218)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timja** [comment]
Did this previously work?

**Comment by reasland** [comment]
Correct, it is currently working perfectly on prior version 155.v745ce80af7ea

So for my uses currently I just rolled back to that version

**Comment by timja** [comment]
ping @reasland do you know how to set this up?

**Comment by timja** [comment]
I can't reproduce this,

Using latest LTS: 2.289.1
Downloaded a fresh version of the CLI

```
wget http://localhost:6322/jenkins/jnlpJars/jenkins-cli.jar -O jenkins-cli.jar
```

```
➜  azure-test-env git:(master) ✗ java -jar jenkins-cli.jar -s http://localhost:6322/jenkins/  -ssh -user me@timja2.onmicrosoft.com -i /Users/timja/.ssh/id_rsa
Jun 16, 2021 7:39:48 AM io.jenkins.cli.shaded.org.apache.sshd.common.util.security.AbstractSecurityProviderRegistrar getOrCreateProvider
INFO: getOrCreateProvider(EdDSA) created instance of io.jenkins.cli.shaded.net.i2p.crypto.eddsa.EdDSASecurityProvider
Jun 16, 2021 7:39:48 AM io.jenkins.cli.shaded.org.apache.sshd.common.io.DefaultIoServiceFactoryFactory getIoServiceProvider
INFO: No detected/configured IoServiceFactoryFactory using Nio2ServiceFactoryFactory
Jun 16, 2021 7:39:48 AM io.jenkins.cli.shaded.org.apache.sshd.client.config.hosts.ConfigFileHostEntryResolver reloadHostConfigEntries
INFO: resolveEffectiveResolver(me@timja2.onmicrosoft.com@localhost:2222) loaded 4 entries from /Users/timja/.ssh/config
  add-job-to-view
    Adds jobs to view.
  apply-configuration
    Apply YAML configuration to instance
  build
    Builds a job, and optionally waits until its completion.
```
