### ISSUE TITLE
Exporting jenkins.authorizationStrategy fails for configuration-as-code plugin

### ISSUE THREAD

**Issue by aglorei** [jenkinsci/azure-ad-plugin#23]
Exporting a master configuration-as-code yaml file using the [configuration-as-code plugin](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/migrate.md#export-existing-configuration) fails at the `authorizationStrategy` section with an error relating to `AzureAdMatrixAuthorizationStrategy`. I'm unsure about whether this is a bug to file on azure-ad-plugin side, or with the configuration-as-code plugin. Feel free to yell at me if it's the latter.
```
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy: "FAILED TO EXPORT hudson.model.Hudson#authorizationStrategy:\
    \ \nio.jenkins.plugins.casc.ConfiguratorException: Cannot find configurator for\
    \ type class com.microsoft.jenkins.azuread.AzureAdMatrixAuthorizationStrategy\n\
    \tat io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry$1.load(DefaultConfiguratorRegistry.java:97)\n\
    \tat io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry$1.load(DefaultConfiguratorRegistry.java:93)\n\
    \tat com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)\n\
    \tat com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)\n\
    \tat com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)\n\
    \tat com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)\n\t\
    at com.google.common.cache.LocalCache.get(LocalCache.java:3965)\n\tat com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3969)\n\
    \tat com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4829)\n\
    \tat io.jenkins.plugins.casc.impl.DefaultConfiguratorRegistry.lookupOrFail(DefaultConfiguratorRegistry.java:70)\n\
    \tat io.jenkins.plugins.casc.ConfigurationContext.lookupOrFail(ConfigurationContext.java:74)\n\
    \tat io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:154)\n\
    \tat io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.describe(HeteroDescribableConfigurator.java:43)\n\
    \tat io.jenkins.plugins.casc.Attribute.describe(Attribute.java:188)\n\tat io.jenkins.plugins.casc.core.JenkinsConfigurator.describe(JenkinsConfigurator.java:70)\n\
    \tat io.jenkins.plugins.casc.core.JenkinsConfigurator.describe(JenkinsConfigurator.java:25)\n\
    \tat io.jenkins.plugins.casc.ConfigurationAsCode.export(ConfigurationAsCode.java:406)\n\
    \tat io.jenkins.plugins.casc.ConfigurationAsCode.doExport(ConfigurationAsCode.java:396)\n\
    \tat java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)\n\
    \tat org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)\n\t\
    at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)\n\
    \tat org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)\n\
    \tat org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)\n\tat org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)\n\
    \tat org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)\n\tat org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)\n\
    \tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)\n\
    \tat org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)\n\tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:734)\n\
    \tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:864)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)\n\
    \tat org.kohsuke.stapler.Stapler.service(Stapler.java:238)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\
    \tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)\n\t\
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)\n\
    \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)\n\
    \tat com.cloudbees.devoptics.deliver.jira.ApiProxyFilter.doFilter(ApiProxyFilter.java:47)\n\
    \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)\n\
    \tat org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)\n\
    \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)\n\
    \tat io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)\n\
    \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)\n\
    \tat io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)\n\
    \tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)\n\
    \tat jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)\n\tat\
    \ hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)\n\t\
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)\n\t\
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)\n\
    \tat hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)\n\
    \tat hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)\n\
    \tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\
    \tat hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)\n\
    \tat hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)\n\
    \tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)\n\
    \tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)\n\
    \tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)\n\
    \tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)\n\
    \tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)\n\
    \tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)\n\
    \tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)\n\
    \tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)\n\
    \tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)\n\
    \tat org.eclipse.jetty.server.Server.handle(Server.java:531)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)\n\
    \tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)\n\
    \tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)\n\
    \tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)\n\tat org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)\n\
    \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)\n\
    \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)\n\
    \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)\n\
    \tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)\n\
    \tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)\n\
    \tat winstone.BoundedExecutorService.lambda$scheduleNext$0(BoundedExecutorService.java:80)\n\
    \tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\
    \tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\
    \tat java.lang.Thread.run(Thread.java:748)\n"
```

**Comment by timja** [comment]
The `matrix-auth` plugin now has support for configuration-as-code (https://github.com/jenkinsci/matrix-auth-plugin/pull/48)
A similar PR is likely needed here

**Comment by drpebcak** [comment]
@gavinfish any movement on this?

**Comment by gomesp** [comment]
If I understand correctly, this plugin does not yet support CasC, right? I have compared it to the [matrix-auth-plugin](https://github.com/jenkinsci/matrix-auth-plugin/blob/master/src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/GlobalMatrixAuthorizationStrategyConfigurator.java) and it seems that the plugin needs to export an attribute to the ConfigurationContext.

Is there a plan to support CasC in the next release?

**Comment by gavinfish** [comment]
This feature grows more and more important. I have started to look into it.

**Comment by gomesp** [comment]
Thanks @gavinfish. 

If it helps, this is an example of the CasC usage with the matrix-auth-plugin: https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos/global-matrix-auth

I never wrote any integration with the CasC plugin, but it seems that a plugin can expose attributes in the CasC context that hook into your plugin configuration classes (as per the example in my previous comment).

Thanks for looking into it!

**Comment by gomesp** [comment]
Thanks for the update @gavinfish. I've noticed that the new plugin version has just been released. I'll test it today and send an update!

**Comment by gomesp** [comment]
I have just tested the export configuration and the config as code setup and both are working fine. I hope @aglorei will be satisfied with the outcome.

Thanks again @gavinfish !

**Comment by gomesp** [comment]
I have applied the optionalClaims to AAD as instructed in the wiki and I am now getting this stack trace after I applied the configuration (rather permissive at the moment).

Is there something I am missing @gavinfish ?

```
jenkins:
    azure:
      clientId: "${azure-ad-client-id}"
      clientSecret: "${azure-ad-client-secret}"
      tenant: "${azure-ad-tenant-id}"
  authorizationStrategy:
    azureAdMatrix:
      permissions:
        - "Overall/Read:anonymous"
        - "Overall/Administer:anonymous"
```

```
java.lang.IllegalStateException: Can't extract id_token
	at com.microsoft.jenkins.azuread.AzureSecurityRealm.doFinishLogin(AzureSecurityRealm.java:200)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
```

**Comment by gavinfish** [comment]
@gomesp I think you should add `securityRealm` under jenkins?

**Comment by gavinfish** [comment]
I tried with the exported yaml file with some basic modification(remove something not support now), it works fine to me.

**Comment by gomesp** [comment]
Sorry, you're correct @gavinfish. The error was because the administrator of my Azure AD instance has accidentally removed a setting while applying the optional claims.
