### ISSUE TITLE
No hudson.security.AuthorizationStrategy implementation found for azureAdMatrix

### ISSUE THREAD

**Issue by cfsb-jrose** [jenkinsci/azure-ad-plugin#390]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Docker image: jenkins/jenkins:lts

### Reproduction steps

Here is a sample of my casc.yaml file:
```
jenkins:
  authorizationStrategy:
    azureAdMatrix:
      permissions:
        - "GROUP:Overall/Read:Jenkins-Users"
        - "GROUP:Overall/Administer:Jenkins-Admins"
  securityRealm:
    azureSecurityRealm:
      clientid: "${JENKINS_SAML_CLIENT_ID}"
      clientsecret: "${JENKINS_SAML_SECRET_VALUE}"
      tenant: "${JENKINS_SAML_TENANT_ID}"
      cacheduration: 0
      fromrequest: true
```
The actual values are provided via environment variables. If I bring up an interactive prompt, I am able `echo` the values without issue.

### Expected Results

Log into Jenkins as an Azure authenticated user

### Actual Results

```
java.lang.IllegalArgumentException: No hudson.security.AuthorizationStrategy implementation found for azureAdMatrix
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$lookupDescriptor$11(HeteroDescribableConfigurator.java:211)
	at io.vavr.control.Option.orElse(Option.java:321)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lookupDescriptor(HeteroDescribableConfigurator.java:210)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:84)
	at io.vavr.Tuple2.apply(Tuple2.java:238)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:350)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:776)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:712)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:776)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:761)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:637)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:306)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:298)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:109)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:115)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:185)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1164)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:290)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:49)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1199)
	at jenkins.model.Jenkins.<init>(Jenkins.java:987)
	at hudson.model.Hudson.<init>(Hudson.java:86)
	at hudson.model.Hudson.<init>(Hudson.java:82)
	at hudson.WebAppMain$3.run(WebAppMain.java:247)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:264)
```

**Comment by timja** [comment]
Possibly the plugin failed to load? is there another stacktrace further up?

**Comment by cfsb-jrose** [comment]
Funny enough, I was looking into that and noticed plugin failures:
```
2023-03-10T16:39:49.746-05:00 | java.io.IOException: Failed to load: Azure AD Plugin (azure-ad 313.v14b_f37ff114d)
-- | --
  | 2023-03-10T16:39:49.746-05:00 | - Failed to load: Azure SDK API Plugin (azure-sdk 118.v43f74dd9ca_dc)
  | 2023-03-10T16:39:49.746-05:00 | at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:994)
  | 2023-03-10T16:39:49.746-05:00 | at hudson.PluginManager$2$1$1.run(PluginManager.java:555)
  | 2023-03-10T16:39:49.746-05:00 | at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:177)
  | 2023-03-10T16:39:49.746-05:00 | at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
  | 2023-03-10T16:39:49.746-05:00 | at jenkins.model.Jenkins$5.runTask(Jenkins.java:1164)
  | 2023-03-10T16:39:49.746-05:00 | at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
  | 2023-03-10T16:39:49.746-05:00 | at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
  | 2023-03-10T16:39:49.746-05:00 | at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
  | 2023-03-10T16:39:49.746-05:00 | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  | 2023-03-10T16:39:49.746-05:00 | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  | 2023-03-10T16:39:49.746-05:00 | at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by timja** [comment]
that part of the log doesn't say why it failed but it should be in the full log

**Comment by cfsb-jrose** [comment]
I am installing the plugins when I build my docker image from `jenkins/jenkins:lts`
I am going through the logs and will start pinning the plugins and see if that helpls.
If the issue persists, I will provide more logs.

**Comment by cfsb-jrose** [comment]
After reviewing the logs more closely, I have determined that the issue was with the plugins failing to start when setting the entire jenkins home directory (e.g. `/var/jenkins_home`) as persistent. The solution was to make specific folders (e.g. `/var/jenkins_home/jobs`) persistent and allow plugins as well as `jenkins.war` to deploy clean each time.
