### ISSUE TITLE
Exception When Clicking Login

### ISSUE THREAD

**Issue by liamfoneill** [jenkinsci/azure-ad-plugin#4]
Hello,

I have setup the plugin as per the instructions. However I have 2 question:

1. In the roles assignment, am for users/groups once I have selected Azure Active Directory roles and I want to add a user/group what am I supposed to type? I have tried: Username, Display Name, Object Id (GUID) of a single user and also groups. Each on gets added but with a grey strikethrough, as if Jenkins cannot resolve the name. Can you please tell me what value I am supposed to enter here? Is there supposed to be a grey strikethrough or is the name supposed to resolve?
2. I get this exception when I login, can you please help me troubleshoot?

org.jose4j.lang.UnresolvableKeyException: Unable to find a suitable verification key for JWS w/ header {"typ":"JWT","alg":"RS256","x5t":"UofUjPYyYQ68lWwN_JX-hMyh08o","kid":"UofUjPYyYQ68lWwN_JX-hMyh08o"} from JWKs [org.jose4j.jwk.RsaJsonWebKey{kty=RSA, kid=z44wMdHu8wKsumrbfaK98qxs5YI, use=sig, n=p3HhMQsqmgSjeiDsZ1ay-UAFgFMdBYgGGkGa2L0ew6_q3b2x9Ccdru_amVp1HXV2FVwbpK0HYsTSRvWIiCRRT-AgMSIlap7qlg8-iYvdFIJsorf84-sRN9Iq3F1pKD-W9vqsitcEbzljHCLSS2vUKSb7itwjc_AKjky3cX5ndMupQESZNTbiwanM9dAJ7K87pURXN66lS_q9u7wxWvjc3iLEp25PU_06moGDMe5BWuD6Rb_pdFM1plm2FOUhMbxURrwjTZLZDhXKix3NysxCZGnvkxMDZgp2pN7FMqZYppcUhwYJu8wSbfmwh8hXOJDxgxIQL7sYGiHeTaDYEVGC0Q, e=AQAB, x5c=[MIIDBTCCAe2gAwIBAgIQaD0+a2FNl5JMaE2/7KUP5zANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTE3MTEyODAwMDAwMFoXDTE5MTEyOTAwMDAwMFowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKdx4TELKpoEo3og7GdWsvlABYBTHQWIBhpBmti9HsOv6t29sfQnHa7v2pladR11dhVcG6StB2LE0kb1iIgkUU/gIDEiJWqe6pYPPomL3RSCbKK3/OPrETfSKtxdaSg/lvb6rIrXBG85Yxwi0ktr1Ckm+4rcI3PwCo5Mt3F+Z3TLqUBEmTU24sGpzPXQCeyvO6VEVzeupUv6vbu8MVr43N4ixKduT1P9OpqBgzHuQVrg+kW/6XRTNaZZthTlITG8VEa8I02S2Q4VyosdzcrMQmRp75MTA2YKdqTexTKmWKaXFIcGCbvMEm35sIfIVziQ8YMSEC+7GBoh3k2g2BFRgtECAwEAAaMhMB8wHQYDVR0OBBYEFGpho/kx4FeBzTTBIbYVWfFdGIblMA0GCSqGSIb3DQEBCwUAA4IBAQBgaeYvuV4sYJZNPXbxN6FIc0oA4bCg1+DFalT3qzW0bFbl7pXP5YPY/adZlT8+cTznjMgzPPvcXaQdcytR16YqHJVX0ik67NrrQ3g0TtGLc42SuzE+6awryiLQY0Zd799bJwrRcDZUqm/6jKOEOd+utf+3o+VU57w+n7iQLuSL1mKYGMsyzMYCj6xVtYl75iam86leT0/tlXHJ8oqxU5w3xVY6P7v0Sz2UteQNQvhKi6R1/cjfiJUp+OzHpaEor6ls7HSvojY2zm1DIaH6EBp2L9TBFt8IALAEN5hX6XYpKmCHRUlzYwoWo7YwzKiot0XdbDW+zPKGPKtIlbg6cw/+], x5t=z44wMdHu8wKsumrbfaK98qxs5YI}, org.jose4j.jwk.RsaJsonWebKey{kty=RSA, kid=SSQdhI1cKvhQEDSJxE2gGYs40Q0, use=sig, n=pJUB90EMxiNjgkVz5CLLUuG5bYwirL2LXfVsq_nnY686WzbinkvFnNs6LvrJ6DWD5NV1-0Tq2eZj7WU8H9ytmDPsRnJ0b49gRCJYOg6-SdOe9Tl0lB0IBJE1aWh3OdCVrZLE4LH4-LGIDrkwnCV8dKFkO3EIUYPaEysL4g4wLx-TCfpMWE37XC09P-nBRVkRNcihrzY38_MC42NkRdDwByZemXkQKddnn5Y5o4rVzPGqQy3vjmTjKolYEIBYa7n3yF0848MG0k338bjnyceJgmZzjxttkWTVDikQXSldbu3QCrCAlipbWPUAXaZK8buY8LP80G4U_wx4LuZ_Krq5OQ, e=AQAB, x5c=[MIIDBTCCAe2gAwIBAgIQHJ7yHxNEM7tBeqcRTMBhhTANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTE4MDEwODAwMDAwMFoXDTIwMDEwOTAwMDAwMFowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKSVAfdBDMYjY4JFc+Qiy1LhuW2MIqy9i131bKv552OvOls24p5LxZzbOi76yeg1g+TVdftE6tnmY+1lPB/crZgz7EZydG+PYEQiWDoOvknTnvU5dJQdCASRNWlodznQla2SxOCx+PixiA65MJwlfHShZDtxCFGD2hMrC+IOMC8fkwn6TFhN+1wtPT/pwUVZETXIoa82N/PzAuNjZEXQ8AcmXpl5ECnXZ5+WOaOK1czxqkMt745k4yqJWBCAWGu598hdPOPDBtJN9/G458nHiYJmc48bbZFk1Q4pEF0pXW7t0AqwgJYqW1j1AF2mSvG7mPCz/NBuFP8MeC7mfyq6uTkCAwEAAaMhMB8wHQYDVR0OBBYEFFVWt/4iTcBiWk+EX1dCKZGoAlBQMA0GCSqGSIb3DQEBCwUAA4IBAQCJrLUiCfldfDFhZLG08DpLcwpn8Mvhm61ZpPANyCawRgaoBOsxFJew1qpC2wfXh3yUwJEIkkTGXAsiWENkeqmjd2XXQwZuIHIo5/KyZLfo2m1CmEH/QXL6uRx1f8liPr4efC8H+7/sduf6nPfk0UpNsAHA6RxJFy2jg2wHU+Ux4jK4Gc5d/rJPhJhvyS9Zax1hbTlf+N32ZvS780VMDb/nf2LdtACL0ya/+KSDGVXS3GhS9FLEXrBNjq921ghVIFJhPzm54yfeupIwz+zfISoTHIYw37i7iNUbkvDrm14a27pwLS/tfSuJHKcGPt1sjMu6SS/pf1BlvdoFkKdLLaUb], x5t=SSQdhI1cKvhQEDSJxE2gGYs40Q0}, org.jose4j.jwk.RsaJsonWebKey{kty=RSA, kid=2S4SCVGs8Sg9LS6AqLIq6DpW-g8, use=sig, n=oZ-QQrNuB4ei9ATYrT61ebPtvwwYWnsrTpp4ISSp6niZYb92XM0oUTNgqd_C1vGN8J-y9wCbaJWkpBf46CjdZehrqczPhzhHau8WcRXocSB1u_tuZhv1ooAZ4bAcy79UkeLiG60HkuTNJJC8CfaTp1R97szBhuk0Vz5yt4r5SpfewIlBCnZUYwkDS172H9WapQu-3P2Qjh0l-JLyCkdrhvizZUk0atq5_AIDKRU-A0pRGc-EZhUL0LqUMz6c6M2s_4GnQaScv44A5iZUDD15B6e8Apb2yARohkWmOnmRcTVfes8EkfxjzZEzm3cNkvP0ogILyISHKlkzy2OmlU6iXw, e=AQAB, x5c=[MIIDKDCCAhCgAwIBAgIQBHJvVNxP1oZO4HYKh+rypDANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDExhsb2dpbi5taWNyb3NvZnRvbmxpbmUudXMwHhcNMTYxMTE2MDgwMDAwWhcNMTgxMTE2MDgwMDAwWjAjMSEwHwYDVQQDExhsb2dpbi5taWNyb3NvZnRvbmxpbmUudXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQChn5BCs24Hh6L0BNitPrV5s+2/DBhaeytOmnghJKnqeJlhv3ZczShRM2Cp38LW8Y3wn7L3AJtolaSkF/joKN1l6GupzM+HOEdq7xZxFehxIHW7+25mG/WigBnhsBzLv1SR4uIbrQeS5M0kkLwJ9pOnVH3uzMGG6TRXPnK3ivlKl97AiUEKdlRjCQNLXvYf1ZqlC77c/ZCOHSX4kvIKR2uG+LNlSTRq2rn8AgMpFT4DSlEZz4RmFQvQupQzPpzozaz/gadBpJy/jgDmJlQMPXkHp7wClvbIBGiGRaY6eZFxNV96zwSR/GPNkTObdw2S8/SiAgvIhIcqWTPLY6aVTqJfAgMBAAGjWDBWMFQGA1UdAQRNMEuAEDUj0BrjP0RTbmoRPTRMY3WhJTAjMSEwHwYDVQQDExhsb2dpbi5taWNyb3NvZnRvbmxpbmUudXOCEARyb1TcT9aGTuB2Cofq8qQwDQYJKoZIhvcNAQELBQADggEBAGnLhDHVz2gLDiu9L34V3ro/6xZDiSWhGyHcGqky7UlzQH3pT5so8iF5P0WzYqVtogPsyC2LPJYSTt2vmQugD4xlu/wbvMFLcV0hmNoTKCF1QTVtEQiAiy0Aq+eoF7Al5fV1S3Sune0uQHimuUFHCmUuF190MLcHcdWnPAmzIc8fv7quRUUsExXmxSX2ktUYQXzqFyIOSnDCuWFm6tpfK5JXS8fW5bpqTlrysXXz/OW/8NFGq/alfjrya4ojrOYLpunGriEtNPwK7hxj1AlCYEWaRHRXaUIW1ByoSff/6Y6+ZhXPUe0cDlNRt/qIz5aflwO7+W8baTS4O8m/icu7ItE=], x5t=2S4SCVGs8Sg9LS6AqLIq6DpW-g8}] obtained from https://login.microsoftonline.com/common/discovery/keys
	at org.jose4j.keys.resolvers.HttpsJwksVerificationKeyResolver.resolveKey(HttpsJwksVerificationKeyResolver.java:83)
	at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:205)
Caused: org.jose4j.jwt.consumer.InvalidJwtException: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.UnresolvableKeyException: Unable to find a suitable verification key for JWS w/ header {"typ":"JWT","alg":"RS256","x5t":"UofUjPYyYQ68lWwN_JX-hMyh08o","kid":"UofUjPYyYQ68lWwN_JX-hMyh08o"} from JWKs [org.jose4j.jwk.RsaJsonWebKey{kty=RSA, kid=z44wMdHu8wKsumrbfaK98qxs5YI, use=sig, n=p3HhMQsqmgSjeiDsZ1ay-UAFgFMdBYgGGkGa2L0ew6_q3b2x9Ccdru_amVp1HXV2FVwbpK0HYsTSRvWIiCRRT-AgMSIlap7qlg8-iYvdFIJsorf84-sRN9Iq3F1pKD-W9vqsitcEbzljHCLSS2vUKSb7itwjc_AKjky3cX5ndMupQESZNTbiwanM9dAJ7K87pURXN66lS_q9u7wxWvjc3iLEp25PU_06moGDMe5BWuD6Rb_pdFM1plm2FOUhMbxURrwjTZLZDhXKix3NysxCZGnvkxMDZgp2pN7FMqZYppcUhwYJu8wSbfmwh8hXOJDxgxIQL7sYGiHeTaDYEVGC0Q, e=AQAB, x5c=[MIIDBTCCAe2gAwIBAgIQaD0+a2FNl5JMaE2/7KUP5zANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTE3MTEyODAwMDAwMFoXDTE5MTEyOTAwMDAwMFowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKdx4TELKpoEo3og7GdWsvlABYBTHQWIBhpBmti9HsOv6t29sfQnHa7v2pladR11dhVcG6StB2LE0kb1iIgkUU/gIDEiJWqe6pYPPomL3RSCbKK3/OPrETfSKtxdaSg/lvb6rIrXBG85Yxwi0ktr1Ckm+4rcI3PwCo5Mt3F+Z3TLqUBEmTU24sGpzPXQCeyvO6VEVzeupUv6vbu8MVr43N4ixKduT1P9OpqBgzHuQVrg+kW/6XRTNaZZthTlITG8VEa8I02S2Q4VyosdzcrMQmRp75MTA2YKdqTexTKmWKaXFIcGCbvMEm35sIfIVziQ8YMSEC+7GBoh3k2g2BFRgtECAwEAAaMhMB8wHQYDVR0OBBYEFGpho/kx4FeBzTTBIbYVWfFdGIblMA0GCSqGSIb3DQEBCwUAA4IBAQBgaeYvuV4sYJZNPXbxN6FIc0oA4bCg1+DFalT3qzW0bFbl7pXP5YPY/adZlT8+cTznjMgzPPvcXaQdcytR16YqHJVX0ik67NrrQ3g0TtGLc42SuzE+6awryiLQY0Zd799bJwrRcDZUqm/6jKOEOd+utf+3o+VU57w+n7iQLuSL1mKYGMsyzMYCj6xVtYl75iam86leT0/tlXHJ8oqxU5w3xVY6P7v0Sz2UteQNQvhKi6R1/cjfiJUp+OzHpaEor6ls7HSvojY2zm1DIaH6EBp2L9TBFt8IALAEN5hX6XYpKmCHRUlzYwoWo7YwzKiot0XdbDW+zPKGPKtIlbg6cw/+], x5t=z44wMdHu8wKsumrbfaK98qxs5YI}, org.jose4j.jwk.RsaJsonWebKey{kty=RSA, kid=SSQdhI1cKvhQEDSJxE2gGYs40Q0, use=sig, n=pJUB90EMxiNjgkVz5CLLUuG5bYwirL2LXfVsq_nnY686WzbinkvFnNs6LvrJ6DWD5NV1-0Tq2eZj7WU8H9ytmDPsRnJ0b49gRCJYOg6-SdOe9Tl0lB0IBJE1aWh3OdCVrZLE4LH4-LGIDrkwnCV8dKFkO3EIUYPaEysL4g4wLx-TCfpMWE37XC09P-nBRVkRNcihrzY38_MC42NkRdDwByZemXkQKddnn5Y5o4rVzPGqQy3vjmTjKolYEIBYa7n3yF0848MG0k338bjnyceJgmZzjxttkWTVDikQXSldbu3QCrCAlipbWPUAXaZK8buY8LP80G4U_wx4LuZ_Krq5OQ, e=AQAB, x5c=[MIIDBTCCAe2gAwIBAgIQHJ7yHxNEM7tBeqcRTMBhhTANBgkqhkiG9w0BAQsFADAtMSswKQYDVQQDEyJhY2NvdW50cy5hY2Nlc3Njb250cm9sLndpbmRvd3MubmV0MB4XDTE4MDEwODAwMDAwMFoXDTIwMDEwOTAwMDAwMFowLTErMCkGA1UEAxMiYWNjb3VudHMuYWNjZXNzY29udHJvbC53aW5kb3dzLm5ldDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKSVAfdBDMYjY4JFc+Qiy1LhuW2MIqy9i131bKv552OvOls24p5LxZzbOi76yeg1g+TVdftE6tnmY+1lPB/crZgz7EZydG+PYEQiWDoOvknTnvU5dJQdCASRNWlodznQla2SxOCx+PixiA65MJwlfHShZDtxCFGD2hMrC+IOMC8fkwn6TFhN+1wtPT/pwUVZETXIoa82N/PzAuNjZEXQ8AcmXpl5ECnXZ5+WOaOK1czxqkMt745k4yqJWBCAWGu598hdPOPDBtJN9/G458nHiYJmc48bbZFk1Q4pEF0pXW7t0AqwgJYqW1j1AF2mSvG7mPCz/NBuFP8MeC7mfyq6uTkCAwEAAaMhMB8wHQYDVR0OBBYEFFVWt/4iTcBiWk+EX1dCKZGoAlBQMA0GCSqGSIb3DQEBCwUAA4IBAQCJrLUiCfldfDFhZLG08DpLcwpn8Mvhm61ZpPANyCawRgaoBOsxFJew1qpC2wfXh3yUwJEIkkTGXAsiWENkeqmjd2XXQwZuIHIo5/KyZLfo2m1CmEH/QXL6uRx1f8liPr4efC8H+7/sduf6nPfk0UpNsAHA6RxJFy2jg2wHU+Ux4jK4Gc5d/rJPhJhvyS9Zax1hbTlf+N32ZvS780VMDb/nf2LdtACL0ya/+KSDGVXS3GhS9FLEXrBNjq921ghVIFJhPzm54yfeupIwz+zfISoTHIYw37i7iNUbkvDrm14a27pwLS/tfSuJHKcGPt1sjMu6SS/pf1BlvdoFkKdLLaUb], x5t=SSQdhI1cKvhQEDSJxE2gGYs40Q0}, org.jose4j.jwk.RsaJsonWebKey{kty=RSA, kid=2S4SCVGs8Sg9LS6AqLIq6DpW-g8, use=sig, n=oZ-QQrNuB4ei9ATYrT61ebPtvwwYWnsrTpp4ISSp6niZYb92XM0oUTNgqd_C1vGN8J-y9wCbaJWkpBf46CjdZehrqczPhzhHau8WcRXocSB1u_tuZhv1ooAZ4bAcy79UkeLiG60HkuTNJJC8CfaTp1R97szBhuk0Vz5yt4r5SpfewIlBCnZUYwkDS172H9WapQu-3P2Qjh0l-JLyCkdrhvizZUk0atq5_AIDKRU-A0pRGc-EZhUL0LqUMz6c6M2s_4GnQaScv44A5iZUDD15B6e8Apb2yARohkWmOnmRcTVfes8EkfxjzZEzm3cNkvP0ogILyISHKlkzy2OmlU6iXw, e=AQAB, x5c=[MIIDKDCCAhCgAwIBAgIQBHJvVNxP1oZO4HYKh+rypDANBgkqhkiG9w0BAQsFADAjMSEwHwYDVQQDExhsb2dpbi5taWNyb3NvZnRvbmxpbmUudXMwHhcNMTYxMTE2MDgwMDAwWhcNMTgxMTE2MDgwMDAwWjAjMSEwHwYDVQQDExhsb2dpbi5taWNyb3NvZnRvbmxpbmUudXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQChn5BCs24Hh6L0BNitPrV5s+2/DBhaeytOmnghJKnqeJlhv3ZczShRM2Cp38LW8Y3wn7L3AJtolaSkF/joKN1l6GupzM+HOEdq7xZxFehxIHW7+25mG/WigBnhsBzLv1SR4uIbrQeS5M0kkLwJ9pOnVH3uzMGG6TRXPnK3ivlKl97AiUEKdlRjCQNLXvYf1ZqlC77c/ZCOHSX4kvIKR2uG+LNlSTRq2rn8AgMpFT4DSlEZz4RmFQvQupQzPpzozaz/gadBpJy/jgDmJlQMPXkHp7wClvbIBGiGRaY6eZFxNV96zwSR/GPNkTObdw2S8/SiAgvIhIcqWTPLY6aVTqJfAgMBAAGjWDBWMFQGA1UdAQRNMEuAEDUj0BrjP0RTbmoRPTRMY3WhJTAjMSEwHwYDVQQDExhsb2dpbi5taWNyb3NvZnRvbmxpbmUudXOCEARyb1TcT9aGTuB2Cofq8qQwDQYJKoZIhvcNAQELBQADggEBAGnLhDHVz2gLDiu9L34V3ro/6xZDiSWhGyHcGqky7UlzQH3pT5so8iF5P0WzYqVtogPsyC2LPJYSTt2vmQugD4xlu/wbvMFLcV0hmNoTKCF1QTVtEQiAiy0Aq+eoF7Al5fV1S3Sune0uQHimuUFHCmUuF190MLcHcdWnPAmzIc8fv7quRUUsExXmxSX2ktUYQXzqFyIOSnDCuWFm6tpfK5JXS8fW5bpqTlrysXXz/OW/8NFGq/alfjrya4ojrOYLpunGriEtNPwK7hxj1AlCYEWaRHRXaUIW1ByoSff/6Y6+ZhXPUe0cDlNRt/qIz5aflwO7+W8baTS4O8m/icu7ItE=], x5t=2S4SCVGs8Sg9LS6AqLIq6DpW-g8}] obtained from https://login.microsoftonline.com/common/discovery/keys): JsonWebSignature{"typ":"JWT","alg":"RS256","x5t":"UofUjPYyYQ68lWwN_JX-hMyh08o","kid":"UofUjPYyYQ68lWwN_JX-hMyh08o"}->eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IlVvZlVqUFl5WVE2OGxXd05fSlgtaE15aDA4byIsImtpZCI6IlVvZlVqUFl5WVE2OGxXd05fSlgtaE15aDA4byJ9.eyJhdWQiOiI2YTVhYmY1YS0yYjJiLTRhNmYtOWRhYi05NTVmNjc3YWEzODQiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zOGVjZTk0YS02MWQwLTRhZmQtODY0Yy0yNDQ0Y2Q3YTNhYmQvIiwiaWF0IjoxNTE3OTM3NzU0LCJuYmYiOjE1MTc5Mzc3NTQsImV4cCI6MTUxNzk0MTY1NCwiYWlvIjoiQVVRQXUvOEdBQUFBOEwzQ2tYSVVsaE0rc05xY0xQMVhzQ3Nnd0RKc05idnFQU3lrZXE3aVdnMkUzL3c3V0lzamI2QTM3SHBKbjg0b2RHQWJJK3QzZXE3YVhMVnlGQTQ4S2c9PSIsImFtciI6WyJwd2QiXSwiZW1haWwiOiJsaWFtZm9uZWlsbEBvdXRsb29rLmNvbSIsImZhbWlseV9uYW1lIjoiT1x1MDAyN05laWxsIiwiZ2l2ZW5fbmFtZSI6IkxpYW0iLCJpZHAiOiJsaXZlLmNvbSIsImlwYWRkciI6IjIxMy4xMjEuMTYxLjEyNCIsIm5hbWUiOiJMaWFtIE9cdTAwMjdOZWlsbCIsIm5vbmNlIjoiRWViR1huZklITyIsIm9pZCI6Ijc1NjIyYjBlLTM4OGItNDBmNS05N2UwLTQxNDliYzk5ZDFkZSIsInN1YiI6Imhmc2RoMjdHdW4yWm9hUlViczhkYk9fbW05WVM4aEV3WUc0Y2lYWExMck0iLCJ0aWQiOiIzOGVjZTk0YS02MWQwLTRhZmQtODY0Yy0yNDQ0Y2Q3YTNhYmQiLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2xpYW1mb25laWxsQG91dGxvb2suY29tIiwidXRpIjoib2ZmN0xYNTlsRVN5em9pMnBzWWpBQSIsInZlciI6IjEuMCJ9.X0UdK37QH-nlqgMHBOmftjhigjzhlMdaCBUh99fpz-Nze8vzIUdK0CWp2SUXJmKzrxTY_UYRoDxfBz0Wb_yS1ejEOPRCoC_dP1Ot51VWclQONt-Jix7DKjwzU8bkGRQz1VtkBYnepnFmxbpGvAURQKu20NitSoHq-MapeDYUs6y7zEYswiAAePmbSMwq0lhno9Pz-NCt5B2xY3KeiCNVp1TPnayc1fF4d4gamZ3wPbNhLtdV5HsmkJXyfbBk6EyJ_4RQl9es0MAwschkAYE6N52M_4b_luZ3TeBC-B72lLbS1nB6Q3cnLKk5xKX0EJHITnqpI3mVfxzF0ber-MDPDA]
	at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:261)
	at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:416)
	at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:164)
	at com.microsoft.jenkins.azuread.AzureSecurityRealm.validateAndParseIdToken(AzureSecurityRealm.java:236)
	at com.microsoft.jenkins.azuread.AzureSecurityRealm.doFinishLogin(AzureSecurityRealm.java:202)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
Caused: javax.servlet.ServletException
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:765)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$3.doDispatch(MetaClass.java:209)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:138)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at com.microsoft.jenkins.azuread.AzureSecurityRealm$CrumbExempt.process(AzureSecurityRealm.java:343)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:58)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:92)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by LGDoor** [comment]
1. You can input as `John Smith (00000000-0000-0000-0000-000000000000)` or just the guid. And if the service principal is configured correctly, the autocomplete of the input control will work.
2. Does this always happen? it seems like a problem in Azure.

**Comment by khushil** [comment]
Hello. I think I have the same problem and maybe you've already solved it? I've setup the application and verified it works. However I'm puzzeld as to what I'm meant to enter in the Matrix authorization. I've also tried Object ID of the group, username and so on. What am I really meant to enter?

**Comment by mrdfuse** [comment]
There is autocomplete when adding users/groups in the various security pages in Jenkins? AFAIK that doesn't exist.

**Comment by davidhonig** [comment]
Same in here
`Caused by: org.jose4j.lang.UnresolvableKeyException: Unable to find a suitable verification key for JWS w/ header {"typ":"JWT","alg":"RS256","x5t":"FSimuFrFNoC0sJXGmv13nNZceDc","kid":"FSimuFrFNoC0sJXGmv13nNZceDc"} due to an unexpected exception (javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty) while obtaining or using keys from JWKS endpoint at https://login.microsoftonline.com/common/discovery/keys`

started with `java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`

**Comment by davidhonig** [comment]
That is what I've expected. But I've already tried openjdk vs oracle one, now I want to dig down through the cacerts. I'll post update here if I will solve that.
