### ISSUE TITLE
Login attempts after the first successful one load indefinitely

### ISSUE THREAD

**Issue by UsernameIsAlreadyTakenForReal** [jenkinsci/azure-ad-plugin#614]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

Jenkins: 2.452.3
OS: Linux - 4.18.0-553.16.1.el8_10.x86_64
Java: 17.0.5 - Oracle Corporation (Java HotSpot(TM) 64-Bit Server VM)
---
Office-365-Connector:4.21.5
allure-jenkins-plugin:2.31.1
amazon-ecr:1.114.vfd22430621f5
ansicolor:1.0.4
ant:511.v0a_a_1a_334f41b_
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
asm-api:9.7-33.v4d23ef79fcc8
atlassian-bitbucket-server-integration:4.0.0
audit-trail:361.v82cde86c784e
authentication-tokens:1.53.v1c90fd9191a_b_
authorize-project:1.7.2
aws-credentials:218.v1b_e9466ec5da_
aws-java-sdk:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-api-gateway:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-autoscaling:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-cloudformation:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-cloudfront:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-codebuild:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-codedeploy:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-ec2:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-ecr:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-ecs:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-efs:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-elasticbeanstalk:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-elasticloadbalancingv2:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-iam:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-kinesis:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-lambda:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-logs:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-minimal:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-organizations:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-secretsmanager:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-sns:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-sqs:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-ssm:1.12.767-467.vb_e93f0c614b_6
aws-secrets-manager-credentials-provider:1.214.va_0a_d8268d068
azure-ad:507.vea_a_a_167b_d05c
azure-sdk:174.va_89c1df897d2
badge:1.13
bitbucket:254.v9d8ec33a_7a_42
blueocean:1.27.8
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.8
blueocean-commons:1.27.14
blueocean-config:1.27.14
blueocean-core-js:1.27.14
blueocean-dashboard:1.27.14
blueocean-display-url:2.4.3
blueocean-events:1.27.8
blueocean-git-pipeline:1.27.8
blueocean-github-pipeline:1.27.8
blueocean-i18n:1.27.14
blueocean-jwt:1.27.14
blueocean-personalization:1.27.14
blueocean-pipeline-api-impl:1.27.8
blueocean-pipeline-editor:1.27.8
blueocean-pipeline-scm-api:1.27.8
blueocean-rest:1.27.14
blueocean-rest-impl:1.27.8
blueocean-web:1.27.14
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1178.v969d9eb_c728e
build-metrics:1.3
build-timeout:1.33
build-user-vars-plugin:166.v52976843b_435
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.0
chucknorris:159.vdfe649cb_9c37
cloudbees-bitbucket-branch-source:848.v42c6a_317eda_e
cloudbees-folder:6.858.v898218f3609d
cmakebuilder:4.1.1
command-launcher:115.vd8b_301cc15d0
commons-compress-api:1.26.1-2
commons-httpclient3-api:3.1-3
commons-lang3-api:3.16.0-82.ve2b_07d659d95
commons-text-api:1.12.0-129.v99a_50df237f7
conditional-buildstep:1.4.3
config-file-provider:959.vcff671a_4518b_
configuration-as-code:1836.vccda_4a_122a_a_e
configuration-as-code-groovy:1.1
credentials:1293.vff276f713473
credentials-binding:636.v55f1275c7b_27
crowd2:4.1.0
cvs:2.19.1
dashboard-view:2.517.v776a_b_811a_b_4e
data-tables-api:2.1.4-1
datadog:7.1.2
delivery-pipeline-plugin:1.4.2
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:439.va_3cb_0a_6a_fb_29
docker-workflow:580.vc0c340686b_54
durable-task:568.v8fb_5c57e8417
ec2:1628.v6d7b_fc58b_a_1d
echarts-api:5.5.1-1
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:2.102
envinject:2.919.v009a_a_1067cd0
envinject-api:1.199.v3ce31253ed13
extended-choice-parameter:376.v2e02857547b_a_
extended-read-permission:53.v6499940139e5
favorite:2.221.v19ca_666b_62f5
file-parameters:339.v4b_cc83e11455
flatpickr-api:4.6.13-5.v534d8025a_a_59
font-awesome-api:6.6.0-1
generic-webhook-trigger:1.88.0
git:5.2.0
git-changelog:3.38
git-client:4.5.0
git-parameter:0.9.19
git-server:126.v0d945d8d2b_39
github:1.37.3
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1741.va_3028eb_9fd21
global-build-stats:307.v03dce5a_f8943
gradle:2.12
groovy-postbuild:228.vcdb_cf7265066
gson-api:2.11.0-41.v019fcf6125dc
h2-api:11.1.4.199-30.v1c64e772f3a_c
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
hidden-parameter:237.v4b_df26c7a_f0e
htmlpublisher:1.36
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jacoco:3.3.6
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jenkins-design-language:1.27.14
jersey2-api:2.44-151.v6df377fff741
jira:3.11
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
jnr-posix-api:3.1.19-2
job-dsl:1.87
job-restrictions:0.8
jobConfigHistory:1229.v3039470161a_d
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery:1.12.4-1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1291.v60776881903c
lockable-resources:1255.vf48745da_35d0
mailer:472.vf7c289a_4b_420
mask-passwords:173.v6a_077a_291eb_5
matrix-auth:3.2.2
matrix-project:832.va_66e270d2946
mercurial:1260.vdfb_723cdcc81
metrics:4.2.21-451.vd51df8df52ec
mina-sshd-api-common:2.13.2-125.v200281b_61d59
mina-sshd-api-core:2.10.0-69.v28e3e36d18eb_
monitoring:1.99.0
msbuild:1.34
next-build-number:1.8
node-iterator-api:55.v3b_77d4032326
nodejs:1.6.1
oic-auth:4.324.vfd49d010926b_
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
parameterized-scheduler:255.v73827fcdf618
parameterized-trigger:806.vf6fff3e28c3e
performance:962.v95a_4913d332e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-maven:1345.va_0ef5530a_5ca_
pipeline-maven-api:1421.v610fa_b_e2d60e
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2205.vc9522a_9d5711
pipeline-model-definition:2.2144.v077a_d1928a_40
pipeline-model-extensions:2.2144.v077a_d1928a_40
pipeline-npm:204.v4dc4c2202625
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2205.vc9522a_9d5711
pipeline-stage-view:2.34
pipeline-utility-steps:2.17.0
plain-credentials:182.v468b_97b_9dcb_8
plugin-util-api:4.1.0
postbuild-task:1.9
prism-api:1.29.0-16
pubsub-light:1.18
purge-job-history:1.6
pyenv-pipeline:2.1.2
readonly-parameters:1.0.0
rebuild:332.va_1ee476d8f6d
resource-disposer:0.23
role-strategy:689.v731678c3e0eb_
run-condition:1.7
schedule-build:577.v0613c45b_9eef
scm-api:696.v778d637b_a_762
script-security:1354.va_70a_fe478c7f
semantic-versioning-plugin:1.15
snakeyaml-api:2.2-121.v5a_68b_9300b_d4
sonar:2.17.2
sse-gateway:1.27
ssh-agent:333.v878b_53c89511
ssh-credentials:308.ve4497b_ccd8f4
ssh-slaves:2.916.vd17b_43357ce4
sshd:3.312.v1c601b_c83b_0e
startup-trigger-plugin:2.9.4
stashNotifier:1.439.v202358346a_7d
structs:338.v848422169819
thinBackup:1.18
throttle-concurrents:2.14
timestamper:1.27
token-macro:400.v35420b_922dcb_
toolenv:1.2
trilead-api:2.147.vb_73cc728a_32e
uno-choice:2.8.3
variant:60.v7290fc0eb_b_cd
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3943.v3519a_3260660
workflow-durable-task-step:1364.v2fd76fb_6fd41
workflow-job:1348.v32a_a_f150910e
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:920.v59f71ce16f04
ws-cleanup:0.46
xml-job-to-job-dsl:0.1.13

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux RHEL8

### Reproduction steps

This is possibly not a bug I'm reporting, but rather an ask for help, as I have run out of ideas to try and make it work. If there is another place to pose my question, please let me know.

1. Setup as instructed by documentation (both Azure AD App Registration and Jenkins plugin setup)
2. Setup Azure AD Matrix-based strategy
3. Log in
4. Try to log in with another user OR logout and try to log in again

### Expected Results

For it to work anytime, for any user authorized by AD.

### Actual Results

The first login after the setup works fine. Any subsequent login attempts, by logging out and then trying to log in again OR from another user (in an allowed group) OR from an incognito browser, all of these make Jenkins load indefinitely until the AWS NLB timeouts the session (350 seconds). This happens for about 1hr. After that, another 1 login is possible, with any subsequent ones loading indefinitely, and so on and so forth. 

While the 'test configuration' option always works, the Azure AD Matrix auto-fill doesn't work in a predictable manner. Even when it does, it does not change the main issue described above.

### Anything else?

I followed the Jenkins logs as best as I could (and I'm not particulary good at networking). The failed logins are delayed by a couple of minutes. I saw there is an order that looks like this:

1. REQUEST for /securityRealm/commenceLogin
2. COMMIT for /securityRealm/commenceLogin
3. REQUEST for /securityRealm/finishLogin
4. COMMIT for /securityRealm/finishLogin

On a successful login, it goes through with everything. On a failed one, it stops after the COMMIT on commenceLogin, without any visible error or issue. Moreover, I saw that this (failed) COMMIT used the same HTTP Channel as the successful COMMIT, which was about 19 minutes old at that point. This would probably make sense for the same user, but it happens for a different user as well.

Sorry if that's useless or I missed logs, Jenkins is extremely verbose when prompted to log everything.

**Comment by timja** [comment]
Can you test directly, bypassing the AWS NLB and see if it works?

**Comment by cap-tskukan** [comment]
I am experiencing the same issue.

**Comment by UsernameIsAlreadyTakenForReal** [comment]
Thank you for the answer. I managed to solve the situation by using another plugin. Let me know how if you want to mark this as 'completed' or as 'not planned'.

**Comment by timja** [comment]
Let's go with not planned, there's not information information or troubleshooting information here and if you've worked around it there's nothing actionable here.

**Comment by cf-sewe** [comment]
I have the same issue. I found out that I can extend some timeout values (e.g. in reverse proxy), but since a few weeks the login takes very long time (> 1 min) after the first succesful (and fast) login. Debugging via tcpdump and setting Jenkins log to trace etc. revealed nothing to me.

**Comment by timja** [comment]
Can you get a few thread dumps please? https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-controllers/how-to-generate-a-thread-dump

**Comment by cf-sewe** [comment]
Thank you for the suggestion. I will provide them!

**Comment by cf-sewe** [comment]
I have executed a few thread dumps from Jenkins Script Console:

```
println("Thread dump:\n" + Thread.getAllStackTraces().collect { thread, stack ->
    thread.name + "\n" + stack.collect { "\tat " + it }.join("\n")
}.join("\n\n"))
```

[jenkins_after_login.txt](https://github.com/user-attachments/files/16930291/jenkins_after_login.txt)
[jenkins_before_login.txt](https://github.com/user-attachments/files/16930292/jenkins_before_login.txt)
[jenkins_during_login1.txt](https://github.com/user-attachments/files/16930293/jenkins_during_login1.txt)
[jenkins_during_login2.txt](https://github.com/user-attachments/files/16930294/jenkins_during_login2.txt)
[jenkins_during_login3.txt](https://github.com/user-attachments/files/16930295/jenkins_during_login3.txt)

By comparing jenkins_during_login2 with jenkins_after_login I can see one problematic thread:
<details>
<summary>Click to view more for GET /securityRealm/commenceLogin></summary>
```
Handling GET /securityRealm/commenceLogin from 217.239.248.2 : Jetty (winstone)-62698
	at java.base@21.0.4/java.io.FileInputStream.readBytes(Native Method)
	at java.base@21.0.4/java.io.FileInputStream.read(Unknown Source)
	at java.base@21.0.4/java.io.FilterInputStream.read(Unknown Source)
	at java.base@21.0.4/sun.security.provider.NativePRNG$RandomIO.readFully(Unknown Source)
	at java.base@21.0.4/sun.security.provider.NativePRNG$RandomIO.ensureBufferValid(Unknown Source)
	at java.base@21.0.4/sun.security.provider.NativePRNG$RandomIO.implNextBytes(Unknown Source)
	at java.base@21.0.4/sun.security.provider.NativePRNG$Blocking.engineNextBytes(Unknown Source)
	at java.base@21.0.4/java.security.SecureRandom.nextBytes(Unknown Source)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.CachedRandomBits.<init>(CachedRandomBits.java:67)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:304)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:263)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.RandomStringUtils.next(RandomStringUtils.java:668)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:165)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.RandomStringUtils.next(RandomStringUtils.java:628)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.RandomStringUtils.random(RandomStringUtils.java:129)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.RandomStringUtils.nextAlphanumeric(RandomStringUtils.java:759)
	at PluginClassLoader for commons-lang3-api//org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(RandomStringUtils.java:412)
	at PluginClassLoader for azure-ad//com.microsoft.jenkins.azuread.AzureSecurityRealm.doCommenceLogin(AzureSecurityRealm.java:365)
	at java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/0x00000001008d5c00.invokeVirtual(LambdaForm$DMH)
	at java.base@21.0.4/java.lang.invoke.LambdaForm$MH/0x0000000100c8a800.invoke(LambdaForm$MH)
	at java.base@21.0.4/java.lang.invoke.LambdaForm$MH/0x000000010136d000.invoke(LambdaForm$MH)
	at java.base@21.0.4/java.lang.invoke.Invokers$Holder.invokeExact_MT(Unknown Source)
	at java.base@21.0.4/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:416)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:429)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:211)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:138)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:644)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:61)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
	at org.kohsuke.stapler.MetaClass$2.doDispatch(MetaClass.java:244)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:61)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:827)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:965)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:253)
	at Jenkins Main ClassLoader//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:163)
	at PluginClassLoader for metrics//jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
	at jenkins.util.HttpServletFilter$1.doFilter(HttpServletFilter.java:76)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:160)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:166)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at jenkins.ErrorAttributeFilter.doFilter(ErrorAttributeFilter.java:29)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:160)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:94)
	at jenkins.security.AcegiSecurityExceptionFilter.doFilter(AcegiSecurityExceptionFilter.java:52)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:54)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:145)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:221)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:97)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:63)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:99)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:111)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:172)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:53)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:86)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:31)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at jenkins.security.SuspiciousRequestFilter.doFilter(SuspiciousRequestFilter.java:38)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at Jenkins Main ClassLoader//org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:569)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1384)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1306)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.Server.handle(Server.java:563)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at Jenkins Main ClassLoader//org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at Jenkins Main ClassLoader//org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at Jenkins Main ClassLoader//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base@21.0.4/java.lang.Thread.runWith(Unknown Source)
	at java.base@21.0.4/java.lang.Thread.run(Unknown Source)
```
</details>

**Comment by cf-sewe** [comment]
After upgrade from Jenkins LTS  2.462.1 to 2.462.2 I can't reproduce.
I thought - hey when I already have to administrate Jenkins today, why not update it 😅

**Comment by cf-sewe** [comment]
Thank you, I didnt see that! 
I currently have over 900 entropy in the pool. 
```
$ cat /proc/sys/kernel/random/entropy_avail
954
```

I will check entropy again, should the issue return.
I currently havent installed any extra entropy generator like haveged.

**Comment by timja** [comment]
Thanks I'll close this for now, but if you do encounter please update the issue in case someone else hits it and if `haveged` helps the issue.
