### ISSUE TITLE
Azure Active Directory Matrix-based security breaks job UI

### ISSUE THREAD

**Issue by mhsbb** [jenkinsci/azure-ad-plugin#91]
With Jenkins versions from >= 2.264 the job configuration page is broken. UI elements are placed at wrong positions and it is not possible to save or apply the settings.
The javascript console shows errors about elements not found:

behavior.js:119 TypeError: Cannot read property 'next' of undefined
    at findEnd (hudson-behavior.js:808)
    at hudson-behavior.js:1109
    at Array.forEach (<anonymous>)
    at behavior.js:116
    at Array.forEach (<anonymous>)
    at behavior.js:111
    at Array.forEach (<anonymous>)
    at Object.applySubtree (behavior.js:93)
    at Object.apply (behavior.js:76)
    at behavior.js:71

Switching to an other authorization mode in global settings allows to save the job settings again.
![image](https://user-images.githubusercontent.com/54977443/100587966-8a13e980-32f1-11eb-9b7a-c8a3a24c1b5f.png)
It could be related to the jenkins ui changes from tables to divs (https://issues.jenkins.io/browse/JENKINS-62437), the AD Matrix uses still tables:
![image](https://user-images.githubusercontent.com/54977443/100588094-b7609780-32f1-11eb-8c4c-7364901a06ec.png)

**Comment by certara-tpagden** [comment]
We are running into the same problem. Job settings is unusable, and switching authn schemes is ... less than desirable.

**Comment by sheromon** [comment]
Yes, same here. :-(

**Comment by vladaurosh** [comment]
I've opened [JENKINS-64452](https://issues.jenkins.io/browse/JENKINS-64452)  yesterday, I just figured out that it is already opened here.

**Comment by timja** [comment]
Can someone please test this fix works for them? https://github.com/jenkinsci/azure-ad-plugin/pull/95

**Comment by vladaurosh** [comment]
Hi @timja 
I just tried with azure-commons-1.0.6-rc220.c094849fd287 but issue is still present.

**Comment by timja** [comment]
And my pull request?

**Comment by vladaurosh** [comment]
I thought it was included in azure-commons-1.0.6-rc220.c094849fd287.hpi ?

**Comment by timja** [comment]
Nope hmm build has failed on windows, so no package produced, I’ve retriggered it and will add a link once it passed

**Comment by timja** [comment]
@vladaurosh You need to install:

https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-ad/1.2.1-rc124.b7cb1094d36f/azure-ad-1.2.1-rc124.b7cb1094d36f.hpi
and

https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-commons/1.0.6-rc220.c094849fd287/azure-commons-1.0.6-rc220.c094849fd287.hpi

**Comment by vladaurosh** [comment]
Hi @timja 
I've uploaded new azure-ad pluging but after jenkins restart, my setup is broken (can't login, getting Ops, a problem ocurred ...). :(

**Comment by vladaurosh** [comment]
Got this in Jenkins log
 WARNING o.e.j.s.h.ContextHandler$Context#log: Error while serving https://jenkins.dev.ipan-platform.com/securityRealm/finishLogin
java.lang.ClassNotFoundException: com.google.common.reflect.TypeToken
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1387)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1342)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1089)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Caused: java.lang.NoClassDefFoundError: com/google/common/reflect/TypeToken
        at com.microsoft.rest.Validator.validate(Validator.java:45)
        at com.microsoft.azure.management.graphrbac.implementation.UsersInner.getMemberGroupsWithServiceResponseAsync(UsersInner.java:696)
        at com.microsoft.azure.management.graphrbac.implementation.UsersInner.getMemberGroups(UsersInner.java:642)
        at com.microsoft.jenkins.azuread.AzureCachePool$1.call(AzureCachePool.java:46)
        at com.microsoft.jenkins.azuread.AzureCachePool$1.call(AzureCachePool.java:37)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
Caused: com.google.common.util.concurrent.ExecutionError
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2232)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)
        at com.microsoft.jenkins.azuread.AzureCachePool.getBelongingGroupsByOid(AzureCachePool.java:36)
        at com.microsoft.jenkins.azuread.AzureSecurityRealm.lambda$doFinishLogin$0(AzureSecurityRealm.java:250)
        at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4767)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3568)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2350)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2313)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2228)
Caused: com.google.common.util.concurrent.ExecutionError
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2232)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3965)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4764)
        at com.microsoft.jenkins.azuread.AzureSecurityRealm.doFinishLogin(AzureSecurityRealm.java:247)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
        at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
Caused: java.lang.reflect.InvocationTargetException

**Comment by timja** [comment]
This fixes the above issue: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/azure-ad/1.2.1-rc125.2d07e4f759f0/azure-ad-1.2.1-rc125.2d07e4f759f0.hpi

**Comment by vladaurosh** [comment]
Yes, I can confirm issue is fixed now. 👍
